# Generated by Django 4.2.7 on 2026-03-06 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('application_file', models.FileField(blank=True, null=True, upload_to='leaves/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to='accounts.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='accounts.student')),
            ],
            options={
                'db_table': 'leave_requests',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('section', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('academic_year', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facial_enabled', models.BooleanField(default=False)),
                ('geo_fencing_enabled', models.BooleanField(default=False)),
                ('campus_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('campus_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('allowed_radius_meters', models.IntegerField(default=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
            options={
                'db_table': 'attendance_sessions',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=10)),
                ('semester', models.PositiveSmallIntegerField()),
                ('academic_year', models.CharField(max_length=9)),
                ('is_present', models.BooleanField(default=False)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('facial', 'Facial Recognition'), ('rfid', 'RFID')], default='manual', max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_verified', models.BooleanField(default=False)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to='accounts.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'db_table': 'attendance',
                'indexes': [models.Index(fields=['student', 'subject'], name='attendance_student_700385_idx'), models.Index(fields=['date'], name='attendance_date_d460ba_idx'), models.Index(fields=['semester', 'academic_year'], name='attendance_semeste_7351d9_idx')],
                'unique_together': {('student', 'subject', 'date')},
            },
        ),
    ]
