# Generated by Django 4.2.7 on 2026-04-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='webauthn_enabled',
            field=models.BooleanField(default=False, help_text='Allow students to mark attendance using their device passkey (WebAuthn).'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='method',
            field=models.CharField(choices=[('manual', 'Manual'), ('facial', 'Facial Recognition'), ('rfid', 'RFID'), ('webauthn', 'Passkey (WebAuthn)')], default='manual', max_length=10),
        ),
    ]
