# Generated by Django 4.2.7 on 2026-03-08 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_parentdetail_father_mobile_and_more'),
        ('academics', '0003_subject_branch_subject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Kis branch ka subject hai (auto-enroll ke liye zaruri)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], help_text='Kis semester ka subject hai (auto-enroll ke liye zaruri)', null=True),
        ),
    ]
