# Generated by Django 4.2.7 on 2026-03-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_student_id'),
        ('academics', '0004_alter_subject_branch_alter_subject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this subject belongs to (required for auto-enrollment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], help_text='Semester this subject belongs to (required for auto-enrollment)', null=True),
        ),
    ]
