# Generated by Django 4.2.7 on 2026-03-06 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(help_text='Unique student ID e.g. BCS2024001 — login username bhi yahi hota hai.', max_length=20, primary_key=True, serialize=False)),
                ('enrollment_number', models.CharField(max_length=20, unique=True)),
                ('roll_number', models.CharField(max_length=20)),
                ('rfid_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('registered_photo', models.ImageField(blank=True, help_text='Facial recognition ke liye student ki clear front-facing photo. Admin ya Teacher upload karta hai.', null=True, upload_to='students/face_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], default='single', max_length=10)),
                ('domicile_state', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('academic_year', models.CharField(max_length=9)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.student')),
            ],
            options={
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='PresentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('address_line3', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='present_address', to='accounts.student')),
            ],
            options={
                'db_table': 'present_addresses',
            },
        ),
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('address_line3', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='accounts.student')),
            ],
            options={
                'db_table': 'permanent_addresses',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_otps',
            },
        ),
        migrations.CreateModel(
            name='ParentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_mobile', models.CharField(max_length=15)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_mobile', models.CharField(max_length=15)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_detail', to='accounts.student')),
            ],
            options={
                'db_table': 'parent_details',
            },
        ),
    ]
