# Generated by Django 4.2.7 on 2026-03-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
