# Generated by Django 4.2.7 on 2026-03-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_permanentaddress_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentdetail',
            name='father_mobile',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='parentdetail',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='parentdetail',
            name='mother_mobile',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='parentdetail',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='domicile_state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
