# Generated by Django 4.2.7 on 2026-03-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_parentdetail_father_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(help_text='Unique student ID e.g. BCS2024001 — also used as the login username.', max_length=20, primary_key=True, serialize=False),
        ),
    ]
