# Generated by Django 4.2.7 on 2026-04-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_webauthncredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webauthnchallenge',
            name='challenge',
            field=models.TextField(help_text='base64url-encoded challenge bytes'),
        ),
    ]
